// Kinetic Acoustic Synthesis Engine
// Pure procedural sound engine physically generated by collision data

class ProceduralAudioEngine {
    private audioCtx: AudioContext | null = null;
    private masterGain: GainNode | null = null;
    private isInitialized = false;

    init() {
        if (this.isInitialized) return;
        try {
            this.audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)();
            this.masterGain = this.audioCtx.createGain();
            this.masterGain.gain.value = 0.5; // Master volume
            this.masterGain.connect(this.audioCtx.destination);
            this.isInitialized = true;
        } catch (e: any) {
            console.warn("Audio initialization failed", e);
            alert(`Synthesizer error: ${e.message || ''}`);
        }
    }

    private lastImpactTime: Record<string, number> = {};

    // Impact Audio Math: E_k = 0.5 * m * v^2
    playImpact(velocity: number, mass: number, isBone: boolean) {
        if (!this.audioCtx || !this.masterGain || !this.isInitialized) return;
        
        const nowMs = performance.now();
        const typeKey = isBone ? 'bone' : 'flesh';
        if (this.lastImpactTime[typeKey] && (nowMs - this.lastImpactTime[typeKey] < 50)) {
            return; // Throttle identical impacts to max 20Hz
        }
        
        const energy = 0.5 * mass * (velocity * velocity);
        if (energy < 0.1) return; // Threshold
        
        this.lastImpactTime[typeKey] = nowMs;

        const osc = this.audioCtx.createOscillator();
        const gain = this.audioCtx.createGain();
        const filter = this.audioCtx.createBiquadFilter();

        osc.connect(filter);
        filter.connect(gain);
        gain.connect(this.masterGain);

        const now = this.audioCtx.currentTime;

        if (isBone) {
            // High energy bone collision: spike high frequency attack
            osc.type = 'triangle';
            osc.frequency.setValueAtTime(800 + Math.min(energy * 50, 2000), now);
            osc.frequency.exponentialRampToValueAtTime(100, now + 0.1);
            
            filter.type = 'bandpass';
            filter.frequency.value = 2000;
            filter.Q.value = 1.0;

            gain.gain.setValueAtTime(0, now);
            gain.gain.linearRampToValueAtTime(Math.min(energy * 0.2, 1.0), now + 0.01); // Sharp attack
            gain.gain.exponentialRampToValueAtTime(0.001, now + 0.2);
        } else {
            // Soft tissue slap: low frequency bass resonance
            osc.type = 'sine';
            osc.frequency.setValueAtTime(50 + Math.min(energy * 10, 100), now);
            osc.frequency.exponentialRampToValueAtTime(20, now + 0.3);

            filter.type = 'lowpass';
            filter.frequency.value = 300 + energy * 20;

            gain.gain.setValueAtTime(0, now);
            gain.gain.linearRampToValueAtTime(Math.min(energy * 0.5, 1.0), now + 0.05); // Softer attack
            gain.gain.exponentialRampToValueAtTime(0.001, now + 0.4);
        }

        osc.start(now);
        osc.stop(now + 0.5);
    }

    // Fascia Friction Sonics: sliding friction
    playFriction(velocity: number, wetness: number) {
        if (!this.audioCtx || !this.masterGain || !this.isInitialized) return;
        
        if (velocity < 0.01) return;

        // Use a buffer source with noise for sliding
        const bufferSize = this.audioCtx.sampleRate * 0.2; // 200ms of noise
        const buffer = this.audioCtx.createBuffer(1, bufferSize, this.audioCtx.sampleRate);
        const data = buffer.getChannelData(0);
        for (let i = 0; i < bufferSize; i++) {
            data[i] = Math.random() * 2 - 1; // White noise
        }

        const noiseSource = this.audioCtx.createBufferSource();
        noiseSource.buffer = buffer;

        const filter = this.audioCtx.createBiquadFilter();
        const gain = this.audioCtx.createGain();

        noiseSource.connect(filter);
        filter.connect(gain);
        gain.connect(this.masterGain);

        const now = this.audioCtx.currentTime;

        // Dry friction = high pitched abrasive tearing
        // Saturation/wetmaps = muffled high frequencies, dense heavy sound
        if (wetness > 0.5) {
            filter.type = 'lowpass';
            filter.frequency.value = 400 + (1.0 - wetness) * 800; // Low pass lowers as it gets wetter
        } else {
            filter.type = 'highpass';
            filter.frequency.value = 1000 + (1.0 - wetness) * 4000;
        }

        gain.gain.setValueAtTime(0, now);
        gain.gain.linearRampToValueAtTime(Math.min(velocity * 0.5, 0.8), now + 0.02);
        gain.gain.linearRampToValueAtTime(0.001, now + 0.15);

        noiseSource.start(now);
    }
}

export const proceduralAudio = new ProceduralAudioEngine();
