// Copyright BANNON.

#include "BannonCounterMatrix.h"
#include "GameFramework/Character.h"

UBannonCounterMatrix::UBannonCounterMatrix()
{
	PrimaryComponentTick.bCanEverTick = false;
}

void UBannonCounterMatrix::InterceptMidAir(ACharacter* Attacker, ACharacter* AirborneDefender)
{
	if (!Attacker || !AirborneDefender) return;
	
	// Detect collisions in mid-air
	// E.g., catching a diving opponent into a powerslam by dynamically creating a physics constraint
}

void UBannonCounterMatrix::ApplyPhysicsReversal(ACharacter* Grappler, FVector CurrentImpulse)
{
	if (!Grappler) return;
	
	// Reversals generated by altering the physics impulse vector
	FVector ReversalVector = -CurrentImpulse * 1.2f;
	
	// Apply torque/impulse to both bodies via BannonRagdollComponent 
	// to organically "flip" the interaction using the engine
}
