#!/usr/bin/env node
/* AUTOMATED move -> mocap-clip mapper (NON-MANUAL). Scores every FBX mocap clip (assets/moves/
 * fbx_move_map.json, 182 clips loaded via BANNON_LOAD_FBX_LIBRARY -> STUDIO.clips) against every move
 * in the library (bannon_move_library + mdickie_moves + mdickie_buckle_moves) by token overlap +
 * category + position, and assigns each move its best-matching clip so the engine's studioApplyClipPose
 * ANIMATES it (legibility) instead of physics-only. Output: assets/moves/move_clip_map.json, consumed
 * at runtime. Re-run any time new clips or moves are added — zero manual authoring.
 *   node tools/mocap/auto_map_moves.cjs
 */
const fs=require('fs'), path=require('path');
const M=path.join(__dirname,'..','..','assets','moves');
const rd=f=>{ try{ return JSON.parse(fs.readFileSync(path.join(M,f),'utf8')); }catch(e){ return null; } };
const fbx=rd('fbx_move_map.json')||{clips:[]};
const clips=fbx.clips||[];
const libs=['bannon_move_library.json','mdickie_moves.json','mdickie_buckle_moves.json'];
const CATMAP={ grapple:['grapple','throw','slam','suplex','powerbomb','ddt','driver'], strike:['strike','punch','kick','chop','clothesline','forearm'],
  dive:['dive','aerial','splash','moonsault','senton','crossbody'], submission:['submission','hold','lock','choke'] };
const toks=s=>String(s||'').toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2);
function score(move, clip){
  const mt=new Set(toks(move.name).concat(toks(move.mdickie),toks(move.pos),toks(move.from)));
  const ct=toks(clip.clip).concat(toks(clip.engine),toks(clip.cat),toks(clip.pos));
  let s=0; for(const t of ct) if(mt.has(t)) s+=3;
  // category affinity
  const mcat=(move.dive?'dive':move.sub?'submission':move.kind==='strike'?'strike':'grapple');
  if((clip.cat||'').includes(mcat)||(CATMAP[mcat]||[]).some(k=>(clip.clip||'').toLowerCase().includes(k))) s+=2;
  // engine-key exact (resolveGrapPos target)
  if(move.pos && clip.engine && move.pos.toUpperCase()===clip.engine.toUpperCase()) s+=6;
  return s;
}
const out={}; let n=0, hit=0;
for(const lf of libs){ const L=rd(lf); if(!L) continue; const arr=Array.isArray(L)?L:(L.moves||L.grapples||[]).concat(L.dives||[],L.strikes||[],L.submissions||[]);
  for(const mv of arr){ if(!mv||!mv.name) continue; n++;
    let best=null,bs=0; for(const c of clips){ const sc=score(mv,c); if(sc>bs){bs=sc;best=c;} }
    if(best && bs>=3){ out[mv.name]={clip:best.clip, engine:best.engine, score:bs}; hit++; }
  } }
fs.writeFileSync(path.join(M,'move_clip_map.json'), JSON.stringify({_note:'AUTO-GENERATED by tools/mocap/auto_map_moves.cjs — move name -> best mocap clip. Consumed at runtime by BANNON_MOVE_LIBRARY.', generated:new Date().toISOString().slice(0,10), count:hit, map:out}, null, 1));
console.log('mapped',hit,'/',n,'moves to mocap clips ->',clips.length,'clips available. wrote assets/moves/move_clip_map.json');
