import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Network, ArrowRight, Activity, Thermometer, ShieldAlert, Target } from 'lucide-react';

const MECHANICS = [
    {
        id: 'leverage',
        label: 'Leverage',
        desc: 'This is the ultimate expression of mechanical advantage. Leverage is the art of usin a small amount of input at the right point in the system to move an impossible amount of weight. When you encounter resistance you do not brute force it; you apply leverage to make the system move for you.',
        icon: <ShieldAlert className="w-5 h-5 text-emerald-400 group-hover:text-white transition-colors" />,
        color: 'border-emerald-500',
        bg: 'bg-emerald-950/30'
    },
    {
        id: 'calibrate',
        label: 'Calibrate',
        desc: 'When the grid offers resistance it is simply a data point indicating the system is out of alignment. You do not get angry at the machine. You calibrate the variables. You adjust the tension until the resistance becomes the fuel for your next move.',
        icon: <Activity className="w-5 h-5 text-fuchsia-400 group-hover:text-white transition-colors" />,
        color: 'border-fuchsia-500',
        bg: 'bg-fuchsia-950/30'
    },
    {
        id: 'direct',
        label: 'Direct',
        desc: 'You do not fight the current. You direct the energy. Resistance is just energy that has not found its path yet. You build the channel and you direct that resistance into the specific pipe that feeds your output.',
        icon: <Network className="w-5 h-5 text-cyan-400 group-hover:text-white transition-colors" />,
        color: 'border-cyan-500',
        bg: 'bg-cyan-950/30'
    },
    {
        id: 'optimize',
        label: 'Optimize',
        desc: 'Resistance is an indicator of unoptimized flow. When you hit a snag you are seeing a bug in the code. You optimize the script. You strip the friction. You make the path of least resistance be the path of highest gain.',
        icon: <ArrowRight className="w-5 h-5 text-amber-400 group-hover:text-white transition-colors" />,
        color: 'border-amber-500',
        bg: 'bg-amber-950/30'
    },
    {
        id: 'amplify',
        label: 'Amplify',
        desc: 'You take the incoming resistance and you amplify the signal. You use the heat generated by the friction to burn brighter. You turn the obstacle into the structure of your own advancement',
        icon: <Thermometer className="w-5 h-5 text-rose-400 group-hover:text-white transition-colors" />,
        color: 'border-rose-500',
        bg: 'bg-rose-950/30'
    },
    {
        id: 'vector',
        label: 'Vector',
        desc: 'Every bit of resistance has a direction. You do not ignore it. You map it. You calculate the trajectory and you align your own vector to slide right through the tension. You use the force of the grid to accelerate your own momentum.',
        icon: <Target className="w-5 h-5 text-indigo-400 group-hover:text-white transition-colors" />,
        color: 'border-indigo-500',
        bg: 'bg-indigo-950/30'
    }
];

export default function KineticResistanceEngine() {
  const [activeMechanic, setActiveMechanic] = useState<string | null>(null);
  const [targetFriction, setTargetFriction] = useState('');
  const [compileLog, setCompileLog] = useState<string[]>([]);
  const [isCompiling, setIsCompiling] = useState(false);

  const handleExecute = () => {
    if (!activeMechanic || !targetFriction.trim()) return;
    
    setIsCompiling(true);
    
    // Intensify global grid pulse
    document.documentElement.style.setProperty('--grid-pulse-duration', '0.5s');
    document.documentElement.style.setProperty('--grid-pulse-max', '1.0');
    
    const mech = MECHANICS.find(m => m.id === activeMechanic);
    const time = new Date().toISOString().split('T')[1].substring(0, 8);
    
    setCompileLog(prev => [`[${time}] LOCKING VECTOR: ${mech?.label.toUpperCase()}`, ...prev]);

    setTimeout(() => {
        setCompileLog(prev => [`[${time}] ANALYZIN FRICTION POINT: ${targetFriction}`, ...prev]);
        
        setTimeout(() => {
            setCompileLog(prev => [`[${time}] EXECUTIN STRUCTURAL MATH... APPLYN ${mech?.label.toUpperCase()} PROTOCOLS.`, ...prev]);
            
            setTimeout(() => {
                setCompileLog(prev => [`[${time}] RESISTANCE CONVERTED INTO FORWARD MOMENTUM. SECTOR MATRIX UPDATED.`, ...prev]);
                setIsCompiling(false);
                setTargetFriction('');
                
                // Restore global grid pulse
                setTimeout(() => {
                    document.documentElement.style.setProperty('--grid-pulse-duration', '4s');
                    document.documentElement.style.setProperty('--grid-pulse-max', '0.8');
                }, 1000);
            }, 1000);
        }, 1000);
    }, 800);
  };

  useEffect(() => {
    return () => {
      document.documentElement.style.setProperty('--grid-pulse-duration', '4s');
      document.documentElement.style.setProperty('--grid-pulse-max', '0.8');
    };
  }, []);

  return (
    <div className="flex flex-col h-full bg-[#0a0a0a] text-white p-4">
      <div className="flex items-center gap-2 mb-4 border-b border-[#222] pb-3">
        <Activity className="w-5 h-5 text-emerald-400" />
        <h2 className="font-semibold text-gray-200">Kinetic Resistance Engine</h2>
      </div>

      <div className="flex flex-col gap-2 mb-6">
          <p className="text-xs text-gray-400 border border-[#222] bg-[#111] p-3 rounded-lg font-mono">
            Resistance is necessary for forward motion. Without the resistance of the ground beneath your feet you cannot walk. This engine maps unoptimized friction and converts it directly into momentum.
          </p>
          <div className="text-sm font-black text-white italic pl-2 border-l-2 border-emerald-500 uppercase tracking-wide">
            "We are not victims of the world. We are the creators of it."
          </div>
      </div>

      <div className="flex flex-col gap-4 flex-1 overflow-y-auto pr-2 pb-4">
        
        {/* Input Target */}
        <div className="flex flex-col gap-2">
            <label className="text-xs text-gray-400 font-bold uppercase tracking-widest">
                Target Friction Loop
            </label>
            <input 
                value={targetFriction}
                onChange={e => setTargetFriction(e.target.value)}
                placeholder="Describe the current grid resistance or block..."
                className="w-full bg-[#111] border border-[#333] rounded-lg p-3 text-sm focus:outline-none focus:border-emerald-500 font-mono transition-colors"
            />
        </div>

        {/* Structural Term Selection */}
        <div className="flex flex-col gap-2 mt-2">
            <label className="text-xs text-gray-400 font-bold uppercase tracking-widest">
                Lock Structural Mechanic
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {MECHANICS.map((mech) => (
                    <button
                        key={mech.id}
                        onClick={() => setActiveMechanic(mech.id)}
                        className={`group flex items-start gap-3 p-3 rounded-xl border text-left transition-all ${
                            activeMechanic === mech.id 
                                ? `${mech.color} ${mech.bg}` 
                                : 'border-[#333] bg-[#111] hover:border-gray-500'
                        }`}
                    >
                        <div className={`p-2 rounded-lg bg-[#0a0a0a] border border-[#222]`}>
                            {mech.icon}
                        </div>
                        <div className="flex flex-col">
                            <span className={`text-sm font-bold uppercase tracking-wider ${activeMechanic === mech.id ? 'text-white' : 'text-gray-300 group-hover:text-white'}`}>
                                {mech.label}
                            </span>
                            <span className="text-xs text-gray-500 leading-relaxed mt-1">
                                {mech.desc}
                            </span>
                        </div>
                    </button>
                ))}
            </div>
        </div>

        <button 
            disabled={!activeMechanic || !targetFriction.trim() || isCompiling}
            onClick={handleExecute}
            className="w-full mt-4 bg-zinc-900 border border-emerald-900/50 hover:bg-emerald-900/30 disabled:opacity-50 text-emerald-400 p-4 rounded-xl text-sm font-bold flex items-center justify-center gap-2 transition-colors uppercase tracking-widest outline-none"
        >
            {isCompiling ? 'Compiling Vector...' : 'Execute Mechanical Conversion'}
            {!isCompiling && <ArrowRight className="w-4 h-4" />}
        </button>

        {/* Compile Log */}
        {compileLog.length > 0 && (
            <div className="mt-6 bg-black border border-[#222] rounded-xl p-4 flex flex-col gap-2">
                <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-2 flex items-center gap-2">
                    <Network className="w-4 h-4 text-emerald-500" /> Conversion Log
                </h3>
                <div className="flex flex-col gap-1 font-mono text-xs">
                    {compileLog.map((log, i) => (
                        <motion.div 
                            initial={{ opacity: 0, x: -10 }}
                            animate={{ opacity: 1, x: 0 }}
                            key={i} 
                            className={`${i === 0 ? 'text-emerald-400' : 'text-gray-600'}`}
                        >
                            {log}
                        </motion.div>
                    ))}
                </div>
            </div>
        )}

      </div>
    </div>
  );
}
