import { useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import { usePhysicsStore } from '../store/physicsStore';
import * as THREE from 'three';
import { updateRespiratoryAudio } from '../utils/audio';
import { neuroRouter } from '../utils/neurologicalRouter';

export function useAutonomicSystem() {
    useFrame((state, delta) => {
        // Process latency-based nerve queues
        neuroRouter.processNerveQueue();
        
        const store = usePhysicsStore.getState();
        
        // 1. Calculate base stimuli (Sympathetic drive)
        const painStimulus = store.tissueTrauma;
        const pleasureStimulus = store.hypothalamicClock; // Reuse hypothalamicClock as proxy for climax/pleasure
        const thermalStimulus = store.entityTemperature - 37.0; // Positive = Hot
        
        const targetArousal = Math.min(1.0, (pleasureStimulus * 1.5) + (painStimulus * 0.8));
        
        // 2. Saturation physics: smooth escalation, slow parasympathetic decay
        let newSaturation = store.systemSaturation;
        if (targetArousal > newSaturation) {
            newSaturation = THREE.MathUtils.lerp(newSaturation, targetArousal, delta * 0.5); // Fast peak
        } else {
            newSaturation = THREE.MathUtils.lerp(newSaturation, targetArousal, delta * 0.05); // Slow decay
        }
        
        // 3. Metabolic Heat generated by Strain & Arousal
        const targetHeat = 37.0 + (newSaturation * 1.5) + (store.currentStrain * 1.0);
        let newHeat = THREE.MathUtils.lerp(store.metabolicHeat, targetHeat, delta * 0.1);
        
        // Evaporative Cooling (Latent heat of vaporization)
        // Monitor evaporation mass flow rate via perspiration and wetness
        const evaporationRate = store.perspirationLevel * Math.max(0.0, store.entityTemperature - 34.0) * 0.1;
        const latentHeatLoss = evaporationRate * 2.5; // abstract coefficient for thermal mass
        newHeat -= latentHeatLoss * delta;
        newHeat = Math.max(34.0, newHeat); // Don't freeze
        
        // 4. Chest Volume / Respiration (Tidal volume)
        const respirationRate = 12 + (newSaturation * 30) + (painStimulus * 15); // breaths per min
        const breathCycle = (state.clock.elapsedTime * (respirationRate / 60)) * Math.PI * 2;
        const baseVolume = 0.5; // residual
        const amplitude = 0.3 + (newSaturation * 0.2); // deepest breaths at high arousal
        const newChestVol = baseVolume + Math.sin(breathCycle) * amplitude;
        
        // 5. Heart Rate
        const targetHR = 60 + (newSaturation * 100) + (painStimulus * 40);
        const newHR = THREE.MathUtils.lerp(store.entityHeartRate, targetHR, delta * 2.0);

        // Commit to store atomically
        store.setSystemSaturation(newSaturation);
        store.setMetabolicHeat(newHeat);
        store.setChestVolume(newChestVol);
        store.setEntityHeartRate(newHR);
        
        // Procedural Audio hook
        updateRespiratoryAudio(newChestVol, store.currentStrain, newSaturation);
    });
}
