CREATE TABLE chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    message TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Create policy for inserts
CREATE POLICY "Enable insert for authenticated and anon users" ON chat_history FOR INSERT WITH CHECK (true);

-- Create policy for selects
CREATE POLICY "Enable select for authenticated and anon users" ON chat_history FOR SELECT USING (true);
